services:
  postgres:
    image: postgres:16-alpine
    container_name: tes_mkp_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mkp_test}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mkp_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-mkp_test}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: golang:1.25-alpine
    container_name: tes_mkp_migration
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DB_DRIVER: ${DB_DRIVER:-postgres}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-mkp_test}
      GOOSE_DRIVER: ${GOOSE_DRIVER:-postgres}
      GOOSE_DBSTRING: "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-mkp_test}?sslmode=disable"
      GOOSE_MIGRATION_DIR: "./db/migration"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mkp_network
    entrypoint: >
      sh -c '
        if ! command -v goose > /dev/null 2>&1; then
          echo "Installing Goose CLI..."
          go install github.com/pressly/goose/v3/cmd/goose@latest
        fi
        if [ "$$#" -eq 0 ]; then
          echo "Running migration up..."
          goose -dir ./db/migration postgres "$$GOOSE_DBSTRING" up
        else
          exec "$$@"
        fi
      '

volumes:
  postgres_data:
    driver: local

networks:
  mkp_network:
    driver: bridge
