apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  labels:
    app: api-service
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  JWT_SECRET_KEY: "faf1b4adcca7583a0f866d13b44e92f0"
